import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { HelpCircle, Mail, MessageCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';

export function FAQContent() {
  const faqSections = [
    {
      title: 'About Potatopay',
      questions: [
        {
          q: 'What is Potatopay?',
          a: 'Potatopay is an integration service that enables creators to receive financial support from their fans. It isn\'t a live-streaming tool, but it can connect seamlessly with platforms such as YouTube, Twitch, and others.',
        },
        {
          q: 'Can I use Potatopay?',
          a: 'Yes, Potatopay is open to various activities such as game streaming, tutorials, just chatting, etc., as long as they comply with Indian Law. See Terms & Conditions at https://potatopay.co/terms.',
        },
        {
          q: 'I\'m not a streamer. Can I still use Potatopay?',
          a: 'Yes, support is available in your Potatopay account even if it\'s not live. The downside: there\'s no real-time notification when tips come in, but you can check in the \'Transactions\' menu.',
        },
        {
          q: 'What live streaming platforms can be integrated with Potatopay?',
          a: 'Potatopay integrates with broadcasting software that supports \'Browser Source\', such as OBS or Streamlabs.',
        },
        {
          q: 'How can I use Potatopay?',
          a: 'Register using Google-signin, verify your personal details, verify your bank account, setup an overlay for live streaming, attach the QR code and Potatopay link, and receive support. Initial verification is essential for fund disbursement.',
        },
      ],
    },
    {
      title: 'Sending / Receiving Support',
      questions: [
        {
          q: 'Why can\'t I pay directly via Potatopay QR code?',
          a: 'Potatopay QR code is for redirecting you to support page where you can complete the transaction.',
        },
        {
          q: 'What is the minimum support fund that can be disbursed?',
          a: 'The minimum support fund is ₹1, the minimum fund that can be disbursed is ₹10.',
        },
        {
          q: 'Can I refund the support?',
          a: 'Only if the person you supported raise a ticket to refund a transaction. Read our refund policy for more information.',
        },
      ],
    },
    {
      title: 'Personal Data Settings',
      questions: [
        {
          q: 'The email I registered is wrong, can I change it?',
          a: 'Yes, send an email to help@potatopay.co or DM instagram/x.com to change the registered email.',
        },
        {
          q: 'I forgot my 2FA code, how do I get it?',
          a: 'The 2FA code is automatically generated by Google Authenticator and changes periodically. Do not delete the app while 2FA is active on Potatopay.',
        },
        {
          q: 'Can 2FA be disabled?',
          a: 'Yes, you can disable it by going to Profile-Security-Disable 2FA, or you can email or DM to us on Instagram and X.com.',
        },
      ],
    },
    {
      title: 'Fees and other',
      questions: [
        {
          q: 'What fees do I or the supporter have to pay?',
          a: 'Please refer to our Terms & Conditions for detailed fee information.',
        },
        {
          q: 'What is meant by service fee?',
          a: 'Service fee is a small charge applied to transactions. Please refer to our Terms & Conditions for detailed information.',
        },
        {
          q: 'What is meant by service fees borne by the streamer?',
          a: 'When service fees are borne by the streamer, the creator pays the transaction fees instead of the supporter.',
        },
        {
          q: 'What is meant by service fee borne by supporter?',
          a: 'When service fees are borne by the supporter, the person sending support pays the transaction fees in addition to their tip amount.',
        },
        {
          q: 'Where can I ask about anything else that isn\'t listed in the FAQ?',
          a: 'Contact us via email at help@potatopay.co, DM us on Instagram and X.com. For Collaborations, email contact@potatopay.co. Follow us on social media for the latest updates.',
        },
      ],
    },
  ];

  return (
    <div className='space-y-5'>
      {/* FAQ Sections */}
      <div className='space-y-4'>
        {faqSections.map((section, sectionIndex) => (
          <Card
            key={sectionIndex}
            className='border-[3px] border-black bg-white shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-[5px_5px_0px_0px_rgba(0,0,0,1)] transition-all duration-200'
          >
            <CardHeader className='bg-gradient-to-r from-[#828BF8]/30 via-[#828BF8]/20 to-[#828BF8]/10 border-b-[3px] border-black p-4'>
              <CardTitle className='text-lg font-black text-black uppercase tracking-wide flex items-center gap-2'>
                <div className='w-2 h-2 bg-[#FEF18C] border-[2px] border-black rounded-full'></div>
                {section.title}
              </CardTitle>
            </CardHeader>
            <CardContent className='p-0'>
              <Accordion type="multiple" className='space-y-0 divide-y divide-black/10'>
                {section.questions.map((item, index) => {
                  const itemId = `${sectionIndex}-${index}`;
                  return (
                    <AccordionItem key={index} value={itemId} className='border-0 shadow-none bg-transparent hover:shadow-none'>
                      <AccordionTrigger value={itemId} className='p-5'>
                        <div className='flex items-start gap-3 w-full'>
                          <div className='mt-1 flex-shrink-0 w-6 h-6 bg-[#828BF8]/20 border-[2px] border-black rounded-sm flex items-center justify-center group-hover:bg-[#828BF8]/30 transition-colors'>
                            <span className='text-[10px] font-black text-[#828BF8]'>Q</span>
                          </div>
                          <div className='flex-1 min-w-0 text-left'>
                            <h3 className='text-base font-black text-black leading-snug'>{item.q}</h3>
                          </div>
                        </div>
                      </AccordionTrigger>
                      <AccordionContent value={itemId}>
                        <div className='flex items-start gap-2.5'>
                          <div className='mt-1 flex-shrink-0 w-5 h-5 bg-[#FEF18C]/40 border-[2px] border-black rounded-sm flex items-center justify-center'>
                            <span className='text-[9px] font-black text-black'>A</span>
                          </div>
                          <p className='text-sm text-black/75 font-medium leading-relaxed flex-1'>{item.a}</p>
                        </div>
                      </AccordionContent>
                    </AccordionItem>
                  );
                })}
              </Accordion>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Contact Section */}
      <Card className='border-[3px] border-black bg-gradient-to-br from-[#828BF8]/15 via-[#FEF18C]/20 to-[#828BF8]/10 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-[5px_5px_0px_0px_rgba(0,0,0,1)] transition-all duration-200'>
        <CardContent className='p-6'>
          <div className='flex items-start gap-4'>
            <div className='w-12 h-12 bg-black border-[3px] border-black flex items-center justify-center flex-shrink-0 shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]'>
              <MessageCircle className='w-6 h-6 text-[#FEF18C]' />
            </div>
            <div className='flex-1'>
              <h3 className='text-xl font-black text-black uppercase mb-2 tracking-tight'>Still have questions?</h3>
              <p className='text-sm text-black/70 font-semibold mb-5 leading-relaxed'>
                Can't find what you're looking for? Reach out to us and we'll help you out!
              </p>
              <div className='flex flex-wrap gap-3'>
                <Button
                  asChild
                  className='bg-white hover:bg-[#FEF18C] text-black font-black text-sm px-5 py-2.5 border-[3px] border-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] hover:shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-x-0.5 hover:translate-y-0.5 transition-all duration-200'
                >
                  <a href='mailto:help@potatopay.co' className='flex items-center gap-2'>
                    <Mail className='w-4 h-4' />
                    <span>Email Us</span>
                  </a>
                </Button>
                <Button
                  asChild
                  variant='outline'
                  className='bg-white hover:bg-[#828BF8] hover:text-white text-black font-black text-sm px-5 py-2.5 border-[3px] border-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] hover:shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-x-0.5 hover:translate-y-0.5 transition-all duration-200'
                >
                  <a href='/dashboard/tnc' className='flex items-center gap-2'>
                    <span>View Terms & Conditions</span>
                  </a>
                </Button>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

